volumes:
  data:
  static:
  media:

networks:
  default:
    driver: bridge

services:
  django:
    image: sergeynaum/ip_godovich:latest
    container_name: rating
    restart: always
    env_file:
      - docker/env/.env
    depends_on:
      - database
    command: sh -c "poetry run python manage.py collectstatic --no-input &&
              poetry run python manage.py migrate &&
              poetry run gunicorn -c gunicorn_conf.py conf.wsgi"

  nginx:
    container_name: nginx_rating
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - 9000:9000
    volumes:
      - static:/app/static
      - media:/app/media
      - ./docker/nginx/:/etc/nginx/conf.d:ro
    links:
      - django
    depends_on:
      - django


  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - docker/env/.env
    volumes:
      - data:/var/lib/postgresql/data/
