# Generated by Django 4.2 on 2024-03-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comic",
            name="num_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comic",
            name="total_rating",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
